version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###








# services:
#   database:
#     image: mysql
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_DATABASE: tashpistache
#       MYSQL_USER: tashpistacheadmin
#       MYSQL_PASSWORD: test
#       MYSQL_ROOT_PASSWORD: root
#     volumes:
#       - persistent:/var/lib/mysql
#     networks:
#       - default

#   phpmyadmin:
#     image: phpmyadmin
#     restart: unless-stopped
#     environment:
#       PMA_HOST: database
#       PMA_USER: root
#       PMA_PASSWORD: root
#     ports:
#       - "8080:80"
#     depends_on:
#       - database

# volumes:
#   persistent: